---
title: "Plot for matt"
author: "Alex Couzens"
date: "15/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Plotting

#import df
All_Data <- read_excel("All_Data.xlsx", sheet = "Sheet2", 
    col_types = c("numeric", "numeric", "numeric", 
        "text", "text"))
View(df)

df$VAF<-as.numeric(df$VAF)
df$DP<-as.numeric(df$DP)
df$AD<-as.numeric(df$AD)



#Function for SD
data_summary <- function(data, varname, groupnames){
    require(plyr)
    summary_func <- function(x, col){
        c(mean = mean(x[[col]], na.rm=TRUE),
          sd = sd(x[[col]], na.rm=TRUE))
    }
    data_sum<-ddply(data, groupnames, .fun=summary_func,
                    varname)
    data_sum <- plyr::rename(data_sum, c("mean" = varname))
    return(data_sum)
}

#SD of VAF
df2 <- data_summary(df, varname="VAF", 
                    groupnames=c("V1", "DP"))
                    

#DP as numeric
df2$DP<-as.numeric(df2$DP)

##Plot_all VAF% vs DP (error bars for VAF%)
 
p<- ggplot(df2, aes(x=DP, y=VAF, group=V1, color=V1)) + geom_line() + geom_point()+geom_errorbar(aes(ymax=VAF+sd, ymin=pmax(VAF - sd, 0)), width=.2,position=position_dodge(0.05))+theme()+scale_x_continuous(limit=c(0,8000),breaks = seq(0, 8000, by = 250))+theme_classic()+ theme(axis.text.x = element_text(angle=25),)+theme(axis.title.x = element_text(vjust=-0.5),axis.text.x = element_text(angle=45, vjust=0.1))+ylab("VAF (%)")+xlab("Read Depth at Position")+labs(color='Variant') 
p
ggsave("Plot_VAF_DP_ALL.jpeg")






